### ISSUE TITLE
ECCV‘22 Adaptive Feature Interpolation for Low-Shot Image Generation

### ISSUE THREAD

**Issue by dzld00** [DWCTOD/ECCV2022-Papers-with-Code-Demo#1]
Name: Adaptive Feature Interpolation for Low-Shot Image Generation
Paper link：https://arxiv.org/abs/2112.02450 
Code link:  https://github.com/dzld00/Adaptive-Feature-Interpolation-for-Low-Shot-Image-Generation 
Key words: data augmentation; GAN

多谢！

**Comment by DWCTOD** [comment]
收到，感谢推荐
