### ISSUE TITLE
ECCV-2022-C3P: Cross-domain Pose Prior Propagation for Weakly Supervised 3D Human Pose Estimation

### ISSUE THREAD

**Issue by zhangboshen** [DWCTOD/ECCV2022-Papers-with-Code-Demo#2]
Title: C3P: Cross-domain Pose Prior Propagation for Weakly Supervised 3D Human Pose Estimation
Code: https://github.com/wucunlin/C3P
paper: 暂无

**Comment by DWCTOD** [comment]
收到,已添加,感谢推荐
