### ISSUE TITLE
Latent Partition Implicit with Surface Codes for 3D Representation

### ISSUE THREAD

**Issue by chenchao15** [DWCTOD/ECCV2022-Papers-with-Code-Demo#6]
Name: Latent Partition Implicit with Surface Codes for 3D Representation
Paper link：https://arxiv.org/abs/2207.08631
Code link: https://github.com/chenchao15/LPI
Key words: 3D reconstruction, 3D computer vision

感谢！

**Comment by DWCTOD** [comment]
Got it ! Thanks!
