### ISSUE TITLE
Please add the code link for our ECCV22 paper

### ISSUE THREAD

**Issue by akshaykulkarni07** [DWCTOD/ECCV2022-Papers-with-Code-Demo#8]
Hi, 

Thanks for your efforts in compiling and maintaining this list. Could you please add the code link for our ECCV22 paper : Concurrent Subsidiary Supervision for Unsupervised Source-Free Domain Adaptation? The link is https://github.com/val-iisc/StickerDA

Please also consider creating a "Domain Adaptation" section in the readme. I could find at least ~14 papers with the keywords Domain Adaptation, so that could be helpful for readers.

Thanks

**Comment by DWCTOD** [comment]
Got it ! Thanks!
